model_verbosity = "medium"
model_reasoning_summary = "auto"
sandbox_mode = "workspace-write"
web_search = "indexed"

[sandbox_workspace_write]
  network_access = true

  [mcp_servers.pycharm]
    url = "http://127.0.0.1:64462/stream"
