"""Client-frame capture for the perception pipeline."""

from flyff_bot.features.vision.capture import FrameSource, WindowsFrameSource
from flyff_bot.features.vision.detection import (
    BoundingBox,
    Detection,
    DetectionConfig,
    DetectionError,
    DetectionErrorCode,
    Detector,
    OpenCVDnnYoloDetector,
    load_class_names,
)
from flyff_bot.features.vision.loot_ocr import (
    LootEvent,
    LootLogReader,
    LootLogRegion,
    LootOcrConfig,
    LootOcrError,
    LootOcrErrorCode,
    TesseractTextRecognizer,
    TextRecognizer,
    extract_loot_region,
    parse_loot_lines,
    preprocess_loot_region,
)
from flyff_bot.features.vision.models import (
    CapturedFrame,
    ClientPoint,
    ClientSize,
    FrameCaptureError,
    FrameCaptureErrorCode,
    PixelFormat,
    PlayerVitals,
    TargetVerificationMetrics,
)
from flyff_bot.features.vision.target_verification import (
    AnchorOffsetRegion,
    TargetRegion,
    TargetStatus,
    TargetVerificationConfig,
    TargetVerificationResult,
    TargetVerifier,
    extract_anchor_relative_region,
    extract_target_region,
)
from flyff_bot.features.vision.vitals import (
    GaugeRegion,
    PlayerVitalsConfig,
    PlayerVitalsFeed,
    PlayerVitalsReader,
    VitalGaugeType,
)

__all__ = [
    "AnchorOffsetRegion",
    "BoundingBox",
    "CapturedFrame",
    "ClientPoint",
    "ClientSize",
    "Detection",
    "DetectionConfig",
    "DetectionError",
    "DetectionErrorCode",
    "Detector",
    "FrameCaptureError",
    "FrameCaptureErrorCode",
    "FrameSource",
    "GaugeRegion",
    "LootEvent",
    "LootLogReader",
    "LootLogRegion",
    "LootOcrConfig",
    "LootOcrError",
    "LootOcrErrorCode",
    "OpenCVDnnYoloDetector",
    "PixelFormat",
    "PlayerVitals",
    "PlayerVitalsConfig",
    "PlayerVitalsFeed",
    "PlayerVitalsReader",
    "TargetRegion",
    "TargetStatus",
    "TargetVerificationConfig",
    "TargetVerificationMetrics",
    "TargetVerificationResult",
    "TargetVerifier",
    "TesseractTextRecognizer",
    "TextRecognizer",
    "VitalGaugeType",
    "WindowsFrameSource",
    "extract_anchor_relative_region",
    "extract_loot_region",
    "extract_target_region",
    "load_class_names",
    "parse_loot_lines",
    "preprocess_loot_region",
]
