"""Client-frame capture for the perception pipeline."""

from flyff_bot.features.vision.capture import FrameSource, WindowsFrameSource
from flyff_bot.features.vision.detection import (
    BoundingBox,
    Detection,
    DetectionConfig,
    DetectionError,
    DetectionErrorCode,
    Detector,
    OpenCVDnnYoloDetector,
    load_class_names,
)
from flyff_bot.features.vision.loot_ocr import (
    LootEvent,
    LootLogReader,
    LootLogRegion,
    LootOcrConfig,
    LootOcrError,
    LootOcrErrorCode,
    TesseractTextRecognizer,
    TextRecognizer,
    extract_loot_region,
    parse_loot_lines,
    preprocess_loot_region,
)
from flyff_bot.features.vision.models import (
    CapturedFrame,
    ClientPoint,
    ClientSize,
    FrameCaptureError,
    FrameCaptureErrorCode,
    PixelFormat,
)
from flyff_bot.features.vision.target_verification import (
    TargetRegion,
    TargetStatus,
    TargetVerificationConfig,
    TargetVerificationResult,
    TargetVerifier,
    extract_target_region,
)

__all__ = [
    "BoundingBox",
    "CapturedFrame",
    "ClientPoint",
    "ClientSize",
    "Detection",
    "DetectionConfig",
    "DetectionError",
    "DetectionErrorCode",
    "Detector",
    "FrameCaptureError",
    "FrameCaptureErrorCode",
    "FrameSource",
    "LootEvent",
    "LootLogReader",
    "LootLogRegion",
    "LootOcrConfig",
    "LootOcrError",
    "LootOcrErrorCode",
    "OpenCVDnnYoloDetector",
    "PixelFormat",
    "TargetRegion",
    "TargetStatus",
    "TargetVerificationConfig",
    "TargetVerificationResult",
    "TargetVerifier",
    "TesseractTextRecognizer",
    "TextRecognizer",
    "WindowsFrameSource",
    "extract_loot_region",
    "extract_target_region",
    "load_class_names",
    "parse_loot_lines",
    "preprocess_loot_region",
]
