"""Client-frame capture for the perception pipeline."""

from flyff_bot.features.vision.capture import FrameSource, WindowsFrameSource
from flyff_bot.features.vision.detection import (
    BoundingBox,
    Detection,
    DetectionConfig,
    DetectionError,
    DetectionErrorCode,
    Detector,
    OpenCVDnnYoloDetector,
    load_class_names,
)
from flyff_bot.features.vision.models import (
    CapturedFrame,
    ClientPoint,
    ClientSize,
    FrameCaptureError,
    FrameCaptureErrorCode,
    MonsterStatsMetrics,
    MonsterStatsStatus,
    PixelFormat,
    PlayerVitals,
    TargetNameStatus,
    TargetVerificationMetrics,
)
from flyff_bot.features.vision.ocr import (
    OcrError,
    OcrErrorCode,
    TesseractTextRecognizer,
    TextRecognizer,
    resolve_tesseract_executable,
)
from flyff_bot.features.vision.target_verification import (
    AnchorOffsetRegion,
    TargetRegion,
    TargetStatus,
    TargetVerificationConfig,
    TargetVerificationResult,
    TargetVerifier,
    extract_anchor_relative_region,
    extract_target_region,
    load_mob_anchor_templates,
    match_whitelisted_name,
    preprocess_target_name_region,
    resolve_mob_anchor_path,
)
from flyff_bot.features.vision.vitals import (
    GaugeRegion,
    PlayerVitalsConfig,
    PlayerVitalsFeed,
    PlayerVitalsReader,
    VitalGaugeType,
)

__all__ = [
    "AnchorOffsetRegion",
    "BoundingBox",
    "CapturedFrame",
    "ClientPoint",
    "ClientSize",
    "Detection",
    "DetectionConfig",
    "DetectionError",
    "DetectionErrorCode",
    "Detector",
    "FrameCaptureError",
    "FrameCaptureErrorCode",
    "FrameSource",
    "GaugeRegion",
    "MonsterStatsMetrics",
    "MonsterStatsStatus",
    "OcrError",
    "OcrErrorCode",
    "OpenCVDnnYoloDetector",
    "PixelFormat",
    "PlayerVitals",
    "PlayerVitalsConfig",
    "PlayerVitalsFeed",
    "PlayerVitalsReader",
    "TargetNameStatus",
    "TargetRegion",
    "TargetStatus",
    "TargetVerificationConfig",
    "TargetVerificationMetrics",
    "TargetVerificationResult",
    "TargetVerifier",
    "TesseractTextRecognizer",
    "TextRecognizer",
    "VitalGaugeType",
    "WindowsFrameSource",
    "extract_anchor_relative_region",
    "extract_target_region",
    "load_class_names",
    "load_mob_anchor_templates",
    "match_whitelisted_name",
    "preprocess_target_name_region",
    "resolve_mob_anchor_path",
    "resolve_tesseract_executable",
]
